# Generated by Django 4.1.4 on 2022-12-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], default='Order Placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('M', 'Mobiles'), ('F', 'Fashion'), ('H', 'Home'), ('T', 'Toys')], max_length=30),
        ),
    ]
