# Generated by Django 3.2.12 on 2022-12-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_remove_cart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
